### PR TITLE
Fix firehose iam role

### PR DESCRIPTION
**Pull request by Vermyndax**
This fixes a KMS permission problem that existed for delivery to Elasticsearch. This depends on https://github.com/GSA/devsecops-ekk-stack/pull/12 so please do not merge this until after that one is approved and merged (which means security approved Elasticsearch).

### CODE REVIEW

**Review by briankfitzwater — COMMENTED** [review]
Is elasticsearch in our out?

**Comment by Vermyndax** [comment]
It's in if GSA security approves it. I've not yet heard a determination.

**Comment by afeld** [comment]
https://trello.com/c/X8ycMIkj/273-security-evaluation-of-aws-elasticsearch

**Comment by Vermyndax** [comment]
Elasticsearch is in, so this is ready for review.

**Pull request merged**
